import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="w-full flex items-center justify-center">
				<main className="max-w-[450px] bg-red-400 w-full">{children}</main>
			</body>
		</html>
	);
}
