import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="w-full h-screen flex items-center justify-center bg-slate-100">
				<main className="max-w-[414px] h-full w-full px-[18px] bg-white">
					{children}
				</main>
			</body>
		</html>
	);
}
